spring:
  application:
    name: helpservice
  cloud:
    kubernetes:
      config:
        enabled: true
        name: helpservice
      reload:
        enabled: true
        mode: event
        strategy: refresh
server:
  port: 8081

helpservice:
  greet:
    msg: Not initialized.
  reset:
    key: ${RESET_KEY:default} 
  changeable:
    greet:
      msg: Generic msg
        
logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
